/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enote;

import java.awt.Color;
import javax.swing.JPanel;

import com.darkprograms.speech.microphone.Microphone;
import com.darkprograms.speech.recognizer.GSpeechDuplex;
import com.darkprograms.speech.recognizer.GSpeechResponseListener;
import com.darkprograms.speech.recognizer.GoogleResponse;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;

import net.sourceforge.javaflacencoder.FLACFileWriter;

/**
 *
 * @author Manmeet
 */
public class Speechtotext extends javax.swing.JFrame implements GSpeechResponseListener, MouseListener{

    /**
     * Creates new form Speechtotext
     */
    public Speechtotext() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_about = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_imagetopdf = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_speechtotext = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_texttospeech = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        response = new javax.swing.JTextArea();
        decrypt = new javax.swing.JLabel();
        encrypt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(85, 65, 118));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Home_25px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("KG Second Chances Solid", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Home");

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepane.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        btn_about.setBackground(new java.awt.Color(54, 33, 89));
        btn_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aboutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_aboutMousePressed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Info_25px_1.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("KG Second Chances Solid", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("About");

        javax.swing.GroupLayout btn_aboutLayout = new javax.swing.GroupLayout(btn_about);
        btn_about.setLayout(btn_aboutLayout);
        btn_aboutLayout.setHorizontalGroup(
            btn_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_aboutLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_aboutLayout.setVerticalGroup(
            btn_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btn_aboutLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)))
                .addContainerGap())
        );

        sidepane.add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 340, -1));

        jLabel11.setFont(new java.awt.Font("Brusher", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("enote");
        sidepane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 60));

        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 5));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, 10));

        btn_imagetopdf.setBackground(new java.awt.Color(54, 33, 89));
        btn_imagetopdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_imagetopdfMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_imagetopdfMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Image_25px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("KG Second Chances Solid", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Image to PDF");

        javax.swing.GroupLayout btn_imagetopdfLayout = new javax.swing.GroupLayout(btn_imagetopdf);
        btn_imagetopdf.setLayout(btn_imagetopdfLayout);
        btn_imagetopdfLayout.setHorizontalGroup(
            btn_imagetopdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_imagetopdfLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        btn_imagetopdfLayout.setVerticalGroup(
            btn_imagetopdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_imagetopdfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_imagetopdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepane.add(btn_imagetopdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 340, 50));

        btn_speechtotext.setBackground(new java.awt.Color(64, 43, 100));
        btn_speechtotext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_speechtotextMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_speechtotextMousePressed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Microphone_25px.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("KG Second Chances Solid", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Speech to Text");

        javax.swing.GroupLayout btn_speechtotextLayout = new javax.swing.GroupLayout(btn_speechtotext);
        btn_speechtotext.setLayout(btn_speechtotextLayout);
        btn_speechtotextLayout.setHorizontalGroup(
            btn_speechtotextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_speechtotextLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        btn_speechtotextLayout.setVerticalGroup(
            btn_speechtotextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_speechtotextLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_speechtotextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepane.add(btn_speechtotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 50));

        btn_texttospeech.setBackground(new java.awt.Color(64, 43, 100));
        btn_texttospeech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_texttospeechMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_texttospeechMousePressed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ABC_25px_1.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("KG Second Chances Solid", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Text to Speech");

        javax.swing.GroupLayout btn_texttospeechLayout = new javax.swing.GroupLayout(btn_texttospeech);
        btn_texttospeech.setLayout(btn_texttospeechLayout);
        btn_texttospeechLayout.setHorizontalGroup(
            btn_texttospeechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_texttospeechLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel15)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        btn_texttospeechLayout.setVerticalGroup(
            btn_texttospeechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_texttospeechLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_texttospeechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepane.add(btn_texttospeech, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 50));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 350, 768));

        jPanel1.setBackground(new java.awt.Color(98, 63, 158));

        exit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Shutdown_25px.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("KG Second Chances Solid", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Convert your speech into text and save it as a file on your Laptop/PC... ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 1030, 120));

        jPanel2.setBackground(new java.awt.Color(91, 47, 3));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/audio-loop-waves.gif"))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        response.setBackground(new java.awt.Color(0, 0, 0));
        response.setColumns(20);
        response.setFont(new java.awt.Font("KG Second Chances Solid", 0, 18)); // NOI18N
        response.setForeground(new java.awt.Color(255, 255, 255));
        response.setRows(5);
        jScrollPane1.setViewportView(response);

        decrypt.setBackground(new java.awt.Color(0, 0, 0));
        decrypt.setFont(new java.awt.Font("KG Second Chances Solid", 0, 24)); // NOI18N
        decrypt.setForeground(new java.awt.Color(255, 255, 255));
        decrypt.setText("Decrypt");
        decrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decryptMouseClicked(evt);
            }
        });

        save.setBackground(new java.awt.Color(0, 0, 0));
        save.setFont(new java.awt.Font("KG Second Chances Solid", 0, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save As");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        encrypt.setBackground(new java.awt.Color(0, 0, 0));
        encrypt.setFont(new java.awt.Font("KG Second Chances Solid", 0, 24)); // NOI18N
        encrypt.setForeground(new java.awt.Color(255, 255, 255));
        encrypt.setText("Encrypt");
        encrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encryptMouseClicked(evt);
            }
        });

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("KG Second Chances Solid", 0, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });

        pause.setBackground(new java.awt.Color(0, 0, 0));
        pause.setFont(new java.awt.Font("KG Second Chances Solid", 0, 24)); // NOI18N
        pause.setForeground(new java.awt.Color(255, 255, 255));
        pause.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pause.setText("Pause");

        start.setBackground(new java.awt.Color(0, 0, 0));
        start.setFont(new java.awt.Font("KG Second Chances Solid", 0, 24)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("Start");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(start)
                        .addGap(18, 18, 18)
                        .addComponent(pause)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(save)
                        .addGap(159, 159, 159)
                        .addComponent(encrypt)
                        .addGap(18, 18, 18)
                        .addComponent(decrypt)
                        .addGap(18, 18, 18)
                        .addComponent(clear)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(decrypt)
                    .addComponent(encrypt)
                    .addComponent(clear)
                    .addComponent(pause)
                    .addComponent(start))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 1030, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        // TODO add your handling code here:
        setColor(btn_home);
        resetColor(btn_speechtotext);
        resetColor(btn_texttospeech);
        resetColor(btn_imagetopdf);
        resetColor(btn_about);
    }//GEN-LAST:event_btn_homeMousePressed

    private void btn_aboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMousePressed
        // TODO add your handling code here:
        setColor(btn_about);
        resetColor(btn_home);
        resetColor(btn_imagetopdf);
        resetColor(btn_speechtotext);
        resetColor(btn_texttospeech);
    }//GEN-LAST:event_btn_aboutMousePressed

    private void btn_imagetopdfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_imagetopdfMousePressed
        // TODO add your handling code here:
        setColor(btn_imagetopdf);
        resetColor(btn_about);
        resetColor(btn_home);
        resetColor(btn_speechtotext);
        resetColor(btn_texttospeech);
    }//GEN-LAST:event_btn_imagetopdfMousePressed

    private void btn_speechtotextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_speechtotextMousePressed
        // TODO add your handling code here:
        setColor(btn_speechtotext);
        resetColor(btn_texttospeech);
        resetColor(btn_imagetopdf);
        resetColor(btn_about);
        resetColor(btn_home);
    }//GEN-LAST:event_btn_speechtotextMousePressed

    private void btn_texttospeechMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_texttospeechMousePressed
        // TODO add your handling code here:
        setColor(btn_texttospeech);
        resetColor(btn_imagetopdf);
        resetColor(btn_about);
        resetColor(btn_home);
        resetColor(btn_speechtotext);
    }//GEN-LAST:event_btn_texttospeechMousePressed

    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,118));
    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(64,43,100));
    }
    
    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        // TODO add your handling code here:
        if(response.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please speak something...");
        }
        else
        {
            String text=response.getText();
            File file=new File("eNote.txt");
            FileWriter fw;
            try {
                fw = new FileWriter(file);
                fw.write(text);
                fw.flush();
                fw.close();
                JOptionPane.showMessageDialog(null,"Successfully saved to eNote.txt in parent directory.");
            } catch (IOException ex) {
                Logger.getLogger(Speechtotext.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveMouseClicked

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        new Speechtotext().setVisible(false);
        new TexttoSpeech().setVisible(false);
        new Imagetopdf().setVisible(false);
        new About().setVisible(false);
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_speechtotextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_speechtotextMouseClicked
        // TODO add your handling code here:
        new Speechtotext().setVisible(true);
        new TexttoSpeech().setVisible(false);
        new Imagetopdf().setVisible(false);
        new About().setVisible(false);
        new Home().setVisible(false);
    }//GEN-LAST:event_btn_speechtotextMouseClicked

    private void btn_texttospeechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_texttospeechMouseClicked
        // TODO add your handling code here:
        new TexttoSpeech().setVisible(true);
        new Speechtotext().setVisible(false);
        new Imagetopdf().setVisible(false);
        new About().setVisible(false);
        new Home().setVisible(false);
    }//GEN-LAST:event_btn_texttospeechMouseClicked

    private void btn_imagetopdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_imagetopdfMouseClicked
        // TODO add your handling code here:
        new Imagetopdf().setVisible(true);
        new Speechtotext().setVisible(false);
        new TexttoSpeech().setVisible(false);
        new About().setVisible(false);
        new Home().setVisible(false);
    }//GEN-LAST:event_btn_imagetopdfMouseClicked

    private void btn_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseClicked
        // TODO add your handling code here:
        new About().setVisible(true);
        new Speechtotext().setVisible(false);
        new Imagetopdf().setVisible(false);
        new TexttoSpeech().setVisible(false);
        new Home().setVisible(false);
    }//GEN-LAST:event_btn_aboutMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        response.setText("");
        encrypt.setEnabled(true);
        decrypt.setEnabled(true);
        clear.setEnabled(false);
    }//GEN-LAST:event_clearMouseClicked

    static char[] chars={
        'a','b','c','d','e','f','g','h',
        'i','j','k','l','m','n','o','p',
        'q','r','s','t','u','v','w','x',
        'y','z','A','B','C','D','E','F',
        'G','H','I','J','K','L','M','N',
        'O','P','Q','R','S','T','U','V',
        'W','X','Y','Z','0','1','2','3',
        '4','5','6','7','8','9','~','`',
        '!','@','#','$','%','^','&','*',
        '(',')','_','-','+','=','[',']',
        '{','}',';',':','"','<','>',',',
        '.','?','/','|','/',' '
    };
        
    
    private void encryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encryptMouseClicked
        // TODO add your handling code here:
        String text=response.getText();
        int offset=77;
        if(text.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please speak something...");
        }
        else{
        String encrypted=encrypt_result(text,offset);
        System.out.println("Result after encryption:"+encrypted);
        response.setText(encrypted);
        encrypt.setEnabled(false);
        decrypt.setEnabled(true);
        clear.setEnabled(true);
        }
    }//GEN-LAST:event_encryptMouseClicked

    public static String encrypt_result(String text, int offset)
    {
        char[] plain=text.toCharArray();
        
        System.out.println(plain.length);
        System.out.println(chars.length);
        
        for(int i=0;i<plain.length;i++)
        {
            for(int j=0;j<chars.length;j++)
            {
                if(j<=chars.length-offset)
                {
                    if(plain[i]==chars[j])
                    {
                        plain[i]=chars[j+offset];
                        break;
                    }
                }
                    else if(plain[i]==chars[j])
                    {
                        plain[i]=chars[j-(chars.length-offset+1)];
                    }
                }
            }
        return String.valueOf(plain);
    }
    
    private void decryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decryptMouseClicked
        // TODO add your handling code here:
        String text=response.getText();
        int offset=77;
        if(text.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please speak something...");
        }
        else{
        String decrypted=decrypt_result(text,offset);
        System.out.println("Result after decryption:"+decrypted);
        response.setText(decrypted);
        encrypt.setEnabled(true);
        decrypt.setEnabled(false);
        clear.setEnabled(true);
        }
    }//GEN-LAST:event_decryptMouseClicked

    public static String decrypt_result(String cip, int offset)
    {
        char[] cipher=cip.toCharArray();
        
        for(int i=0;i<cipher.length;i++)
        {
            for(int j=0;j<chars.length;j++)
            {
                if(j>=offset && cipher[i]==chars[j])
                {
                    cipher[i]=chars[j-offset];
                    break;
                }
                if(cipher[i]==chars[j]&&j<offset)
                {
                    cipher[i]=chars[(chars.length-offset+1)+j];
                    break;
                }
            }
        }
        return String.valueOf(cipher);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Speechtotext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Speechtotext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Speechtotext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Speechtotext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Speechtotext().setVisible(true);
            }
        });
        
        final Microphone mic = new Microphone(FLACFileWriter.FLAC);
        //Don't use the below google api key , make your own !!! :) 
    
        GSpeechDuplex duplex = new GSpeechDuplex("AIzaSyBOti4mM-6x9WDnZIjIeyEU21OpBXqWBgw");
               
        duplex.setLanguage("en");
        
        pause.setEnabled(false);
        
        start.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent evt) {
		new Thread(() -> {
                	try {
                        	duplex.recognize(mic.getTargetDataLine(), mic.getAudioFormat());
			} catch (Exception ex) {
                            ex.printStackTrace();
			}
		}).start();
		start.setEnabled(false);
		pause.setEnabled(true);
	}
        @Override
        public void mousePressed(MouseEvent e) {//To change body of generated methods, choose Tools | Templates.
        }
        @Override
        public void mouseReleased(MouseEvent e) { //To change body of generated methods, choose Tools | Templates.
        }
        @Override
        public void mouseEntered(MouseEvent e) { //To change body of generated methods, choose Tools | Templates.
        }
        @Override
        public void mouseExited(MouseEvent e) { //To change body of generated methods, choose Tools | Templates.
        }
        });
        
	pause.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent e1) {
		mic.close();
		duplex.stopSpeechRecognition();
		start.setEnabled(true);
		pause.setEnabled(false);
            }
            @Override
            public void mousePressed(MouseEvent e) { //To change body of generated methods, choose Tools | Templates.
            }
            @Override
            public void mouseReleased(MouseEvent e) {//To change body of generated methods, choose Tools | Templates.
            }
            @Override
            public void mouseEntered(MouseEvent e) { //To change body of generated methods, choose Tools | Templates.
            }
            @Override
            public void mouseExited(MouseEvent e) { //To change body of generated methods, choose Tools | Templates.
            }
	});
                
        duplex.addResponseListener(new GSpeechResponseListener() {
			String old_text = "";
			
			public void onResponse(GoogleResponse gr) {
				String output = "";
				output = gr.getResponse();
				if (gr.getResponse() == null) {
					this.old_text = response.getText();
					if (this.old_text.contains("(")) {
						this.old_text = this.old_text.substring(0, this.old_text.indexOf('('));
					}
					System.out.println("Paragraph Line Added");
					this.old_text = ( response.getText() + "\n" );
					this.old_text = this.old_text.replace(")", "").replace("( ", "");
					response.setText(this.old_text);
					return;
				}
				if (output.contains("(")) {
					output = output.substring(0, output.indexOf('('));
				}
				if (!gr.getOtherPossibleResponses().isEmpty()) {
					output = output + " (" + (String) gr.getOtherPossibleResponses().get(0) + ")";
				}
				System.out.println(output);
				response.setText("");
				response.append(this.old_text);
				response.append(output);
			}
		});
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_about;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_imagetopdf;
    private javax.swing.JPanel btn_speechtotext;
    private javax.swing.JPanel btn_texttospeech;
    final javax.swing.JLabel clear = new javax.swing.JLabel();
    private javax.swing.JLabel decrypt;
    public javax.swing.JLabel encrypt;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    static final javax.swing.JLabel pause = new javax.swing.JLabel();
    public static javax.swing.JTextArea response;
    private static final javax.swing.JLabel save = new javax.swing.JLabel();
    private javax.swing.JPanel sidepane;
    static final javax.swing.JLabel start = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    @Override
    public void onResponse(GoogleResponse gr) {
         //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseClicked(MouseEvent e) { //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) { //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) { //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) { //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) { //To change body of generated methods, choose Tools | Templates.
    }
}
